- README.md
> feat: 开发注意

- packages/editor/src/pages/home/lib/components/ReactEditor.tsx
修复编辑器中windows用户使用Ctrl+S保存代码的问题
> fix: 修复windows下代码保存问题

- packages/editor/src/pages/welcome/index.module.less
> fix: 修复编辑器端欢迎页宽度被撑开的问题

- packages/editor/src/api/lib.ts
- packages/editor/src/api/types/index.ts
- packages/editor/src/components/Searchbar/SearchBar.tsx
- packages/editor/src/components/Searchbar/index.module.less
- packages/editor/src/layout/components/Header/index.tsx
- packages/editor/src/pages/home/LibList.tsx
- packages/editor/src/pages/home/PageList.tsx
- packages/editor/src/pages/home/ProjectList.tsx
- packages/editor/src/pages/home/index.module.less
feat: 新增项目、页面和组件搜索刷新功能。新建表单搜索控件、刷新按钮。
fix: 修复新建和分页等问题。将顶部的新建按钮移到各自的页面当中，修复分页栏位置和每页条数的切换问题。
> feat: 新增项目、页面和组件搜索刷新功能，修复新建和分页等问题

- packages/editor/src/api/types/index.ts
- packages/editor/src/components/Searchbar/SearchBar.tsx
- packages/editor/src/components/Searchbar/index.module.less
- packages/editor/src/pages/home/LibList.tsx
- packages/editor/src/pages/home/PageList.tsx
- packages/editor/src/pages/home/ProjectList.tsx
- packages/editor/src/pages/types/index.ts
feat: 增加查看个人和全部数据的按钮，用户登陆默认查看个人创建的项目、页面和组件，但同时支持查看其他用户创建并且开放访问的内容
> feat: 增加查看个人和全部数据的按钮

- packages/editor/src/pages/welcome/index.module.less
**目的**
欢迎页手机端适配，用户体验更佳
**变更内容**
**解决的问题**
**测试**
**开发流程**
3. **提交前的检查**：
**注意事项**
**其他信息**
无
> :lipstick: feat: 欢迎页多端适配

- packages/editor/src/pages/welcome/index.module.less
**目的**
优化欢迎页多端适配
**变更内容**
**解决的问题**
部分字体大小不适配，元素宽度超出问题
**测试**
**开发流程**
3. **提交前的检查**：
**注意事项**
**其他信息**
无
> :lipstick: fix: 优化欢迎页多端适配

- packages/editor/src/components/EventConfig/ActionModal/ActionModal.tsx
- packages/editor/src/components/EventConfig/ActionModal/OpenDrawerAction.tsx
- packages/editor/src/config/components.ts
- packages/editor/src/packages/Functional/Drawer/Drawer.tsx
- packages/editor/src/packages/Functional/Drawer/Schema.tsx
- packages/editor/src/packages/Functional/Drawer/index.tsx
- packages/editor/src/packages/Functional/index.ts
- packages/editor/src/packages/utils/action.ts
- packages/materials/Functional/Drawer/Drawer.tsx
- packages/materials/Functional/Drawer/index.ts
- packages/materials/utils/action.ts
**目的**
新增抽屉物料
**变更内容**
**解决的问题**
**测试**
**开发流程**
3. **提交前的检查**：
**注意事项**
**其他信息**
无
> 🆕 feat: 新增抽屉物料

- packages/editor/src/config/components.ts
- packages/editor/src/packages/Functional/Result/Result.tsx
- packages/editor/src/packages/Functional/Result/Schema.tsx
- packages/editor/src/packages/Functional/Result/index.ts
- packages/editor/src/packages/Functional/index.ts
- packages/editor/src/pages/admin/menu/CreateMenu.tsx
- packages/materials/Functional/Result/Result.tsx
- packages/materials/Functional/Result/index.ts
> feat: 增加 Result 组件

- packages/docs/.vitepress/config.mts
---
about: 修复文档页面的上下页链接导航错误
title: ''
labels: pr
assignees: ''
---
**目的**
修复文档页面的上下页链接导航错误，譬如**项目介绍**的下一页应该是**菜单介绍**，但目前是**账号登录**。
**变更内容**
> fix: 修复文档上下页链接错误

- packages/editor/src/components/FlowNode/FlowNode.tsx
- packages/editor/src/components/FlowNode/index.less
- pnpm-lock.yaml
---
about: 事件流分支节点后支持增加节点
title: ''
labels: pr
assignees: ''
---
**目的**
事件流分支节点后支持增加节点
**变更内容**
> 事件流分支节点后支持增加节点

- packages/editor/src/config/components.ts
- packages/editor/src/packages/Functional/Avatar/Avatar.tsx
- packages/editor/src/packages/Functional/Avatar/Schema.tsx
- packages/editor/src/packages/Functional/Avatar/index.ts
- packages/editor/src/packages/Functional/index.ts
- packages/materials/Functional/Avatar/Avatar.tsx
- packages/materials/Functional/Avatar/index.ts
- packages/materials/Functional/Result/Result.tsx
**目的**
新增 Avatar 物料组件
**变更内容**
**测试**
本地 admin 已验证
> 🆕 feat: 新增头像物料

- packages/editor/src/components/EventConfig/ActionModal/ComponentMethods.tsx
- packages/editor/src/config/components.ts
- packages/editor/src/packages/Basic/QRCode/QRCode.tsx
- packages/editor/src/packages/Basic/QRCode/Schema.tsx
- packages/editor/src/packages/Basic/QRCode/index.ts
- packages/editor/src/packages/Basic/index.ts
- packages/editor/src/packages/FeedBack/Result/Result.tsx
- packages/editor/src/packages/types/index.ts
- packages/materials/Basic/QRCode/QRCode.tsx
- packages/materials/Basic/QRCode/index.ts
**目的**
新增二维码 qrcode 物料组件
**变更内容**
> 🆕 feat: 新增二维码物料

- backend/java/lowcode-api/src/main/java/com/xintr/lowcode/api/util/DateUtil.java
---
title: ''
labels: pr
assignees: ''
---
**目的**
请简要描述这个 Pull Request 的目的和解决的问题。如果这个 PR 相关的 Issue，请附上 Issue 链接。
**变更内容**
**解决的问题**
**测试**
**开发流程**
3. **提交前的检查**：
**注意事项**
**其他信息**
如果有任何其他信息需要提供，请在这里补充说明。
> 调整java代码结构

- backend/java/lowcode-api/src/main/java/com/xintr/lowcode/api/domain/Pages.java
- backend/java/lowcode-api/src/main/java/com/xintr/lowcode/api/dto/MenuDto.java
- packages/docs/src/deploy.md
1、页面Pages新增projectId
2、创建菜单新增是否创建页面字段
3、使用文档新增java代码生成使用说明
---
title: ''
labels: pr
assignees: ''
---
**目的**
请简要描述这个 Pull Request 的目的和解决的问题。如果这个 PR 相关的 Issue，请附上 Issue 链接。
**变更内容**
**解决的问题**
**测试**
**开发流程**
3. **提交前的检查**：
**注意事项**
**其他信息**
如果有任何其他信息需要提供，请在这里补充说明。
> 使用文档新增java代码生成使用说明

- backend/java/lowcode-core/src/main/java/com/xintr/lowcode/core/controller/UserController.java
- backend/java/lowcode-core/src/main/resources/application.yml
---
title: ''
labels: pr
assignees: ''
---
**目的**
兼容处理邮箱配置错误或者未配置的情况，无法拿到注册码
**变更内容**
- [x ] 修改 1：发送邮件接口增加注册码直接输出控制台，即便邮箱服务配置错误也能控制台看到注册码
- [x ] 修改 2：配置文件默认设置false，防止邮箱服务没配置正确而启动不了
**解决的问题**
- [ x] 问题 1：邮箱服务配置错误无法看到注册码无法注册
- [x ] 问题 2：邮箱服务没配置正确而启动不了Java程序
> 兼容处理邮箱配置错误或者未配置的情况，无法拿到注册码

- packages/editor/src/components/ApiConfig/components/BaseSetting.tsx
- packages/editor/src/packages/types/index.ts
- packages/editor/src/packages/utils/handleApi.ts
- packages/editor/src/packages/utils/request.ts
- packages/materials/types/index.ts
- packages/materials/utils/handleApi.ts
- packages/materials/utils/request.ts
---
about: 修正页面接口中的请求逻辑
title: 'fix: 修正DELETE、PUT请求逻辑，新增PATCH请求动词'
labels: pr
assignees: ''
---
**目的**
修正页面接口中的请求逻辑
**变更内容**
**解决的问题**
> fix: 修正DELETE、PUT请求逻辑，新增PATCH请求动词

- packages/editor/src/packages/utils/handleApi.ts
- packages/materials/utils/handleApi.ts
---
about: 修正DELETE、PUT、PATCH请求参数问题
title: ''
labels: pr
assignees: ''
---
**目的**
修正DELETE、PUT、PATCH请求参数问题
**变更内容**
**解决的问题**
> fix: 修正DELETE、PUT、PATCH请求参数问题

- packages/editor/src/pages/feedback/index.module.less
- packages/editor/src/pages/feedback/index.tsx
- packages/editor/src/pages/types/index.ts
> feat: 新增Github ISSUE列表

- packages/editor/src/packages/Page/Page.tsx
---
title: ''
labels: pr
assignees: ''
---
**目的**
想参与到项目中，看到一个 issue 就添加了， [issue 链接](https://github.com/JackySoft/marsview/issues/67)
**变更内容**
**解决的问题**
[issues 期望添加编辑器拖拽能力](https://github.com/JackySoft/marsview/issues/67)
**测试**
**开发流程**
3. **提交前的检查**：
**注意事项**
**其他信息**
如果有任何其他信息需要提供，请在这里补充说明。
> feat: issue #67:添加编辑器画布拖拽能力

- packages/editor/src/components/FloatingCollector/index.tsx
---
title: ''
labels: pr
assignees: ''
---
**目的**
请简要描述这个 Pull Request 的目的和解决的问题。如果这个 PR 相关的 Issue，请附上 Issue 链接。
**变更内容**
**解决的问题**
**测试**
**开发流程**
3. **提交前的检查**：
**注意事项**
**其他信息**
如果有任何其他信息需要提供，请在这里补充说明。
> fix: 修复编辑器中抽屉及弹框收集器map的key设置错误的问题

- packages/editor/src/components/FlowNode/FlowNode.tsx
- packages/editor/src/utils/util.ts
- pnpm-lock.yaml
---
about: 修复分支节点创建时限制逻辑相关问题
title: ''
labels: pr
assignees: ''
---
**目的**
修复分支节点创建时限制逻辑相关问题
**解决的问题**
> 修复分支节点创建时限制逻辑相关问题

- packages/editor/src/pages/login/Login.tsx
- pnpm-lock.yaml
- 感觉没必要放两个 "没有账号，去注册？"，况且第一个按钮没法点击
> feat(editor): 对登录页的一点小小优化
